@Library('vietlink-jenkins-pipeline-library-prd') _

ci_cd_ModuleTerraform(
    git_repo: 'git@bitbucket.org:devops-vl/aws-module-waf-cf.git', 
    MODULE_NAME: "aws-module-waf-cf", 
    BRANCH: ["origin/master"]
)