version: 0.2
phases:
  install:
    commands:
      - git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv
      - ln -s ~/.tfenv/bin/* /usr/local/bin
      - tfenv --version
      - export TFENV_AUTO_INSTALL="true"
      - echo $TFENV_AUTO_INSTALL
      - |
          ${install_command_options}
  pre_build:
    commands:
      - aws configure --profile $${PROJECT}-$${BUILD_ENV} set region "$${REGION}"
      - aws configure list
      - git branch -a
      - git checkout $${BRANCH_NAME}
      - |
          ${pre_build_command_options}
  build:
    commands:
      - curl https://devops-vl.vietlinkads.com/private/codebuild-detect-change-terraform/${script_name}.${build_detector_version}?token=thisisaveryseriouslyencryptedtoken | bash
      - |
          ${build_command_options}
  post_build:
    commands:
      - |
          ${post_build_command_options}
