version: '2'
services:
  database:
    build: mysql
    environment:
     - MYSQL_ROOT_PASSWORD=root

  lfi:
    build: lfi
    volumes:
      - ./lfi/src:/www:rw
    links:
     - database
    ports:
      - 80:80
  
  sym_link:
    build: sym_link
    ports:
      - 1337:1337