build:
	docker-compose --file docker-compose.yml build
up:
	docker-compose --file docker-compose.yml up -d database lfi sym_link
logs:
	docker-compose --file docker-compose.yml logs -f
down:
	docker-compose --file docker-compose.yml down
restart:
	docker-compose --file docker-compose.yml restart