version: '2'
services:
  nginx:
    build: nginx
    environment:
    - NGINX_PORT=80
    links:
      - web
      - sqli
    ports:
      - 80:80
    volumes:
      - ./nginx/src:/zap:rw
      - ./nginx/conf:/etc/nginx/conf.d/

  web:
    build: app_flask
    volumes:
      - ./app_flask/src:/app
    links:
      - database
      - mongo
    environment:
      - passwdMysql=V1etL1nk0waspZap@!
      - MONGODB_CONNSTRING=mongodb://root:V1etL1nk0waspZap@mongo
    depends_on:
      - database
      - mongo

  database:
    build: mysql
    environment:
     - MYSQL_ROOT_PASSWORD=V1etL1nk0waspZap@!

  scaner:
    image: owasp/zap2docker-stable
    volumes:
      - /tmp:/zap/wrk/:rw
    command: "zap-full-scan.py -t http://nginx -J report.json -d"

  sqli:
    build: sqli
    volumes:
      - ./sqli/src:/www:rw
    links:
     - database
    depends_on:
      - database
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=V1etL1nk0waspZap
      - MONGO_INITDB_ROOT_USERNAME=root
    volumes:
      - ./entrypoint/mongodb:/docker-entrypoint-initdb.d/
      
  testing_query_mongo:
    build: testing_query_mongo
    volumes:
      - ./testing_query_mongo:/app/:rw
    command: python /app/query.py
    environment:
      - MONGODB_CONNSTRING=mongodb://root:V1etL1nk0waspZap@mongo