version: '2'
services:
  nginx:
    image: nginx:latest
    environment:
    - NGINX_PORT=80
    links:
      - app_flask
      - sqli
      - lfi
    ports:
      - 80:80
    volumes:
      - ./nginx/src:/zap:rw
      - ./nginx/conf:/etc/nginx/conf.d/

  app_flask:
    build: app_flask
    volumes:
      - ./app_flask/src:/app
    links:
      - database
      - mongo
    environment:
      - passwdMysql=root
      - MONGODB_CONNSTRING=mongodb://root:V1etL1nk0waspZap@mongo

  database:
    build: mysql
    environment:
     - MYSQL_ROOT_PASSWORD=root

  scaner:
    image: owasp/zap2docker-stable
    volumes:
      - /tmp:/zap/wrk/:rw
    command: "zap-full-scan.py -t http://nginx -J report.json -d"

  sqli:
    build: sqli
    volumes:
      - ./sqli/src:/www:rw
    links:
     - database

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=V1etL1nk0waspZap
      - MONGO_INITDB_ROOT_USERNAME=root
    volumes:
      - ./entrypoint/mongodb:/docker-entrypoint-initdb.d/
  
  lfi:
    build: lfi
    volumes:
      - ./lfi/src:/www:rw
    links:
     - database
  
  ssrf:
    build: ssrf
    volumes:
      - ./ssrf/src:/www
    ports:
      - 5000:80
    