version: '2'
services:
  web:
    build: .
    volumes:
      - ./challenge:/app
    ports:
      - 8005:80
  attacker:
    image: python:3-alpine
    command: "python3 -m http.server 8888"
    ports:
      - 8888:80
    depends_on:
      - web
  scaner:
    image: owasp/zap2docker-stable
    # depends_on:
      # - web
    volumes:
      - ./report:/zap/wrk/:rw
    command: "zap-full-scan.py -t http://web -r report.html -d"
    # command: "zap-full-scan.py -t http://web -J report.json -d"

