version: '3.3'
services:
  nginx:
    build: nginx
    ports:
    - "65223:80"
    environment:
    - NGINX_PORT=80
    links:
      - web
    volumes:
      - ./nginx/index:/usr/share/nginx/html:rw
      - ./nginx/conf:/etc/nginx/conf.d/

  web:
    build: app_flask
    volumes:
      - ./app_flask/challenge:/app