version: '2'
networks:
  OwaspZAP: 
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.201.0/24
    driver_opts:
      com.docker.network.bridge.name: OwaspZAP

services:
  nginx:
    build: nginx
    ports:
    - "65223:80"
    environment:
    - NGINX_PORT=80
    links:
      - web
    volumes:
      - ./nginx/index:/usr/share/nginx/html:rw
      - ./nginx/conf:/etc/nginx/conf.d/
    networks:
      OwaspZAP:
        ipv4_address: 172.30.201.10

  web:
    build: app_flask
    volumes:
      - ./app_flask/challenge:/app
    networks:
      - OwaspZAP